import { Inter } from "next/font/google";
import "./globals.css";
import { site_title, backent_url } from "@/app/config/config";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://cdn.staticfile.org/twitter-bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet" />
        <link href="https://cdn.staticfile.net/bootstrap-icons/1.11.3/font/bootstrap-icons.min.css" rel="stylesheet" />
        <script src="https://cdn.staticfile.org/twitter-bootstrap/5.1.3/js/bootstrap.min.js"></script>
        <script src="https://cdn.staticfile.org/popper.js/2.9.3/umd/popper.min.js"></script>
      </head>
      <body className={inter.className}>
        <header>
          <nav id="navigator" className="navbar navbar-expand-lg fixed-top bg-white box-shadow">
            <div className="container-fluid">
              <a className="navbar-brand" href="/">
                <i className="bi bi-database"></i>
                {site_title}
              </a>
              <button className="navbar-toggler bg-purple-700 rounded-3xl" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
                <i className="bi bi-plus-square"></i>
              </button>
              <div className="collapse navbar-collapse" id="mynavbar">
                <ul className="navbar-nav me-auto">
                  <li className="nav-item">
                    <a className="nav-link" href="/">
                      <i className="bi bi-cloud-upload"></i>
                      上传文件
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="/posts/">
                      <i className="bi bi-card-image"></i>
                      图片库
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="/tags/">
                      <i className="bi bi-tags"></i>
                      标签
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="/folders/">
                      <i className="bi bi-folder-symlink"></i>
                      文件夹
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="/search/">
                      <i className="bi bi-search"></i>
                      搜索
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="/admin/">
                      <i className="bi bi-magic"></i>
                      站点管理
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="/">
                      <i className="bi bi-house"></i>
                      账户
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        </header>
        {children}
        <footer>
          <div id="footer-container" className="container-fluid">
            <div id="footer" className="container-fluid">
              <div id="copyright" className="row"></div>

              <div id="copyright" className="row align-middle">
                <p>Copyright © 2023-2024 {site_title}. Powered by Jacky_Blackson. All rights reserved.</p>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
