import 'bootstrap/dist/css/bootstrap.css';
import './globals.css'
import { Inter } from 'next/font/google'
import { site_title } from './config/global';
import Navigator from '@/components/layout/widget/navibar/navigator';
import BodySidebarLayout from '@/components/layout/body_sidebar_layout';
import DefaultSidebar from '@/components/sidebar/default_sidebar';
import Card from '@/components/sidebar/widget/card';
import BiIcon from '@/components/util/bi_icon';
import TreeViewAsync from '@/components/tree/tree_view_async';
import SearchBar from '@/components/sidebar/widget/search_bar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, side }) {

  const tag_rootUrl = 'tags/roots'
  const tag_nodeUrl = "tags"

  const folder_rootUrl = 'folders/roots'
  const folder_nodeUrl = "folders"

  const folder_card = <Card
    title={'文件夹列表'}
    icon={<BiIcon bicode="folder-symlink" />}
    content={
      <div>
        <TreeViewAsync
          rootUrl={folder_rootUrl}
          nodeUrl={folder_nodeUrl}
          icon={<BiIcon bicode="folder" />}
          targetType='folders'
        />
      </div>
    }
  />

  const tag_card = <Card
    title={'标签列表'}
    icon={<BiIcon bicode="tags" />}
    content={
      <div>
        <TreeViewAsync
          rootUrl={tag_rootUrl}
          nodeUrl={tag_nodeUrl}
          icon={<BiIcon bicode="tag" />}
          targetType='tags'
        />
      </div>
    }
  />

  return (
    <html lang="en">
      <head>
        <link href="https://cdn.staticfile.org/twitter-bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet" />
        <link href="https://cdn.staticfile.net/bootstrap-icons/1.11.3/font/bootstrap-icons.min.css" rel="stylesheet" />
        <script src="https://cdn.staticfile.org/twitter-bootstrap/5.1.3/js/bootstrap.min.js" async ></script>
        <script src="https://cdn.staticfile.org/popper.js/2.9.3/umd/popper.min.js" async ></script>
        
      </head>
      <body className={inter.className}>
        <header>
          <Navigator />
        </header>
        <main style={{ marginTop: '100px' }}>
          <div id="basic-container" className="container-fluid">
            <div id="body-container" className="row m-3 il-round-border" style={{ 'height': '100%' }}>

              <div id="content-container" className="col-xxl-9 col-xl-8 col-lg-7">
                <div id="content" className="il-item">
                  {children}
                </div>
              </div>

              <div id="sidebar-container" className="col-xxl-3 col-xl-4 col-lg-5">
                <div id="sidebar-test" className="il-item">
                  <div>
                    <SearchBar />
                    {side}
                    {folder_card}
                    {tag_card}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </main>
        <footer>
          <div id="footer-container" className="container-fluid">
            <div id="footer" className="container-fluid">
              <div id="copyright" className="d-flex justify-content-center">
                <p >Copyright © 2023-2024 {site_title}. Made with ❤ by Jacky_Blackson. All rights reserved.</p>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  )
}