import 'bootstrap/dist/css/bootstrap.css';
import './globals.css'
import { Inter } from 'next/font/google'
import { site_title } from './config/global';
import Navigator from '@/components/layout/widget/navibar/navigator';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://cdn.staticfile.org/twitter-bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet" />
        <link href="https://cdn.staticfile.net/bootstrap-icons/1.11.3/font/bootstrap-icons.min.css" rel="stylesheet" />
        <script src="https://cdn.staticfile.org/twitter-bootstrap/5.1.3/js/bootstrap.min.js"></script>
        <script src="https://cdn.staticfile.org/popper.js/2.9.3/umd/popper.min.js"></script>
      </head>
      <body className={inter.className}>
        <header>
          <Navigator />
        </header>
        <main style={{ "marginTop": "100px" }}>
          {children}
        </main>
        <footer>
          <div id="footer-container" className="container-fluid">
            <div id="footer" className="container-fluid">
              <div id="copyright" className="d-flex justify-content-center">
                <p >Copyright © 2023-2024 {site_title}. Powered by Jacky_Blackson. All rights reserved.</p>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  )
}